"""Add email verification fields to User model

Revision ID: 89972f34b22c
Revises: 
Create Date: 2025-06-22 16:09:18.902838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89972f34b22c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verification_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_verification_token_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verification_token_expires')
        batch_op.drop_column('email_verification_token')

    # ### end Alembic commands ###
